### ISSUE TITLE
Suggestion: Add agnostic definition

### ISSUE THREAD

**Issue by ElizabethFernandes** [ubc-library-rc/intro-docker#1]
At: https://ubc-library-rc.github.io/intro-docker/uses/#what-is-docker-useful-for

Original: "Docker lets you create static and reproducible environments, saved into an image which will run the same way on any computer with Docker set up (agnostic to hardware and operating system)."

Suggestion: "Docker lets you create static and reproducible environments, saved into an image which will run the same way on any computer with Docker set up ([agnostic](https://www.techopedia.com/definition/31685/hardware-agnostic#:~:text=Hardware%2Dagnostic%20systems%20or%20device,to%20both%20hardware%20and%20software.) to hardware and operating system)."

**Comment by chiselinc** [comment]
Great suggestion, thanks @ElizabethFernandes! I've just updated the text with that link.
