### ISSUE TITLE
add description for "the level of binaries and libraries"

### ISSUE THREAD

**Issue by brettdimond** [ubc-library-rc/intro-docker#6]
On the *Origins and High Level Concepts* page, you state "containers sit on top of the host computer’s kernel and merely virtualize from **the level of binaries and libraries** up to the user interface".

For those participants without a background in computer science, a brief description of what is meant by "the level of binaries and libraries" would likely aid comprehension. This information might best be included under the *Computing concepts* section, but could also be addressed within/in close proximity to the above sentence (e.g. "...from the level of binaries and libraries--the part of a computer responsible for [...]--up to the user interface").

**Comment by chiselinc** [comment]
Great point, thanks! Fixed 👍
