### ISSUE TITLE
swap order of "Disambiguating Docker Terms" page and "Main Use Cases" page

### ISSUE THREAD

**Issue by brettdimond** [ubc-library-rc/intro-docker#7]
I think the flow of the course might be improved by presenting the motivational case for why one would want to use Docker in the first place before an exposition of its many ecosystem components. Additionally, the *Disambiguating Docker Terms* page may serve as a better transition between the more conceptual Part I of the course and the more technical Part II.

**Comment by chiselinc** [comment]
Thanks, great point! Swapped 👍
